//Autogenerated by VS from response JSON
//All API responses have the following structure makingthis intermidiate step necessary
/*
 * 
 * {"results":[{"values":[
 * {"value":"val,"key":"keyName"}
 * ]}]}
 * 
 */


namespace WarsawAPI
{
    public class ApiResponseIntermidiate
    {
        public Result[] result { get; set; }

        public void Print()
        {
            foreach (Result r in result)
            {
                foreach(Value v in r.values) { Console.WriteLine(v.value + " " + v.key); }
            }
        }

        
    }

    public class Result
    {
        public Value[] values { get; set; }

        public string GetValueByKey(string key)
        {

            foreach(Value v in values)
            {
                if (v.key == key) return v.value;
            }

            return "";
        }
    }

    public class Value
    {
        public string value { get; set; }
        public string key { get; set; }
    }
}